
title: My Resume
url: 'https://karthik-ranga.github.io/Resume/'
baseurl: 'https://karthikranga.io/' #change it according to your repository name


# Profile information
yourname: Karthik Rangarajan  ## put your name
title: 'ROBOTICS &amp; DRONE ENTHUSIAST'  ## your title
location: New York City, NY


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
instagram: https://www.instagram.com/karthik_kwads/  ## your twitter account url
linkedin: https://www.linkedin.com/in/karthik-rangarajan/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
